[package]
name             = "g6-gui"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace               = true
eframe.workspace               = true
epaint_default_fonts.workspace = true
fontdue.workspace              = true
g6-core.workspace              = true
ksni.workspace                 = true
serde.workspace                = true
serde_json.workspace           = true
x11rb.workspace                = true
